### ISSUE TITLE
How to download dataset using kiuisobj_v1_merged_80K.csv

### ISSUE THREAD

**Issue by FisherYuuri** [ashawkey/objaverse_filter#2]
Hi, I am really comfused about how to use kiuisobj_v1_merged_80K.csv to download your training dataset. I would appreciate if you could send me a tutorial or download the script!

**Comment by LIRIIS** [comment]
same question

**Comment by lclichen** [comment]
I think that's a simple question, but I can share my script if anyone needs it.
```python
import objaverse
import pandas as pd
# pip install objaverse pandas
import multiprocessing
kiui_uids = pd.read_csv("kiuisobj_v1_merged_80K.csv", header=None)
processes = multiprocessing.cpu_count()
uids = kiui_uids[1].values.tolist()
# make sure you have enough disk capacity
objaverse.load_objects(uids, download_processes=processes)
```

**Comment by LiaoLW** [comment]
> I think that's a simple question, but I can share my script if anyone needs it.
> 
> ```python
> import objaverse
> import pandas as pd
> # pip install objaverse pandas
> import multiprocessing
> kiui_uids = pd.read_csv("kiuisobj_v1_merged_80K.csv", header=None)
> processes = multiprocessing.cpu_count()
> uids = kiui_uids[1].values.tolist()
> # make sure you have enough disk capacity
> objaverse.load_objects(uids, download_processes=processes)
> ```

Thank you for your help, objaverse API only downloads glb files. But the implementation of dataset requires RGB and camera pose, is there any pre-processing required before utilize the dataset to train LGM?
